server:
  port: 831

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/vallalkozas
    driverClassName: org.postgresql.Driver
    hikari:
      maximumPoolSize: 10
      minimumIdle: 2
      idleTimeout: 10000
  jpa:
    properties:
      hibernate:
        default_schema: public
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
liquibase:
  changelog:
    location: classpath:database/changelog-master.xml
  schema: public

app:
  szerszam-keszlet:
    szerszam-tipus:
      - id: kezi-szerszam
        megnevezes: Kézi szerszám
      - id: kalapacs
        megnevezes: Kalapács